fix bugs of reduce video size

diff --git a/video-tool b/video-tool
--- a/video-tool
+++ b/video-tool
@@ -1,8 +1,9 @@
 #!/bin/bash
 
+	# v1.0 --(20180815) add reduce_video_size function
 
 ####################################################
-#                 Music_Finder V0.1                #
+#                 Video_Tool V0.1                  #
 #  https://github.com/hessamashari/video-tool.git  #
 ####################################################
 
@@ -18,11 +19,13 @@ white="$(printf '\033[0;37m')"        # white
 # ----------\Find video function\----------
 function find_video() {
 	local inputDir="$1"
-	local IFS=":"
+	local IFS=":" # Use in line 35/36
 
 	read -p "Please enter the name of video : " videoName
 
+	# Separating files that have video format
 	local videoTypes="\.webm$|\.flv$|\.vob$|\.ogg$|\.ogv$|\.drc$|\.gifv$|\.mng$|\.avi$|\.mov$|\.qt$|\.wmv$|\.yuv$|\.rm$|\.rmvb$|/.asf$|\.amv$|\.mp4$|\.m4v$|\.mp*$|\.m?v$|\.svi$|\.3gp$|\.ts$|\.flv$|\.f4v$"
+
 	if [[ "$inputDir" == "/" ]]; then
 		sudo find / -type f -iname "*$videoName*" | grep -E "$videoTypes"
 		local searchDir=$(sudo find / -type f -iname "*$videoName*" | grep -E "$videoTypes")
@@ -31,15 +34,17 @@ function find_video() {
 		local searchDir=$(find "$inputDir" -type f -iname "*$videoName*" | grep -E "$videoTypes")
 	fi
 
+		# Creat file with found videos and change \n to : on it
 		echo $searchDir > $HOME/searchDir
 		sed -i ':a;N;$!ba;s/\n/:/g' $HOME/searchDir
 
+	# Ask for all videos were found
 	for videoPath in $(cat $HOME/searchDir); do
 		echo -e "\n"
 		read -p "${green} Would you like to work with ${orange}'$videoPath'${normal}? [Y/n] "  workWithThis
 
 		if [[ "$workWithThis" == "" || "$workWithThis" == "y" || "$workWithThis" == "Y" ]]; then
-			refer-related-func "$videoPath"
+			refer_related_func "$videoPath"
 		elif [[ "$workWithThis" == "n" || "$workWithThis" == "N" ]]; then
 			continue
 		else
@@ -93,7 +98,7 @@ function select_video_path() {
 		# Read path/to/video
 		read -p "Enter path of the video : " -i "" -e videoPath
 
-		refer-related-func "$videoPath"
+		refer_related_func "$videoPath"
 	else
 		echo -e "${red}Invalid argument!${normal}"
 		exit 1
@@ -108,14 +113,37 @@ function reduce_video_size() {
 		read -p "Do you want to rename the new video? [Y/n] " renameNewVideo
 
 		if [[ "$renameNewVideo" == "" || "$renameNewVideo" == "Y" || "$renameNewVideo" == "y" ]]; then
-			ffmpeg -i "$inputVideo" -vcodec h264 -acodec aac -strict -2
+			read -p "Please write the new name : " newVideoName
+
+			ffmpeg -i "$inputVideo" -vcodec h264 -acodec aac -strict -2 "$newVideoName.mp4"
+
+			if [[ "$?" == "0" ]]; then
+				echo -e "\n"
+				echo -e "${green}Your video is ready : ${orange}$newVideoName${normal}"
+			else
+				echo -e "\n"
+				echo -e "${red} Procces doesn't finish succesfully!${normal}"
+				exit 1
+			fi
 		elif [[ "$renameNewVideo" == "n" || "$renameNewVideo" == "N" ]]; then
+			
 			ffmpeg -i "$inputVideo" -vcodec h264 -acodec aac -strict -2 "$(echo "$inputVideo" | tr '.' ' ').mp4"
 
-			echo -e "${green}\n Your video is ready : ${orange}$(echo "$inputVideo" | tr '.' ' ').mp4${normal}"
+			if [[ "$?" == "0" ]]; then
+				echo -e "\n"
+				eecho -e "${green}Your video is ready : ${orange}$(echo "$inputVideo" | tr '.' ' ').mp4${normal}"
+			else
+				echo -e "\n"
+				echo -e "${red} Procces doesn't finish succesfully!${normal}"
+				exit 1
+			fi
+		else
+			echo -e "${red}Invalid argument!${normal}"
+			exit 1
 		fi
 	else
-		echo -e "${red}\nYou haven't access to ${orange}'$inputVideo'${normal}"
+		echo -e "\n"
+		echo -e "${red}You haven't access to ${orange}'$inputVideo'${normal}"
 		exit 1
 	fi
 }
@@ -126,7 +154,7 @@ function change_vide_format() {
 }
 
 # ----------\Refer to related function\----------
-function refer-related-func() {
+function refer_related_func() {
 	local pathToVideo="$1"
 
 	if [[ "$selectedItem" == "1" ]]; then
