write few of select-video_path function

diff --git a/video-tool b/video-tool
--- a/video-tool
+++ b/video-tool
@@ -17,26 +17,52 @@ white="$(printf '\033[0;37m')"        # white
 
 # ----------\Main function\----------
 function main() {
+	echo -e "ُ${red}+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+${normal}"
 	read -p "${green}What can i do for you ???${normal}
 	1)${orange} Reduce video size.${normal}
 	2)${orange} Change the video format.${normal}
 
 	Enter the number of the option that you selected : " selectedItem
+	echo -e "ُ${red}+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+${normal}"
 	if [[ "$selectedItem" == "1" ]]; then
-		reduce_video_size
+		select_video_path
 	elif [[ "$selectedItem" == "2" ]]; then
 		echo "helo"
+	else
+		echo -e "${red}Invalid argument!${normal}"
+		exit 1
 	fi
 }
 
 # ----------\Select movie function\----------
-function select_video() {
-	echo "hello"
+function select_video_path() {
+	# Ask for video path
+	read -p "Do you want to search video for you {search / s} or you know the video location {location / l} : " searchVideoAnswer
+	echo -e "ُ${red}+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+${normal}"
+
+	if [[ "$searchVideoAnswer" == "search" || "$searchVideoAnswer" == "S" || "$searchVideoAnswer" == "s" ]]; then
+		read -p "Do you like to serach all of your system (Requires root access)? [Y/n] " searchAllSystem
+
+		if [[ "$searchAllSystem" == "" || "$searchAllSystem" == "y" || "$searchAllSystem" == "Y" ]]; then
+			# Search all of file system
+		    echo -e "This operation may take a while!"
+
+		elif [[ "$searchAllSystem" == "n" || "$searchAllSystem" == "N" ]]; then
+			read -p "Do you like search this directory? [Y/n] " workingDirectory
+
+			if [[ "$workingDirectory" == "" || "$workingDirectory" == "y" || "$workingDirectory" == "Y" ]]; then
+				# Search current directory
+	elif [[ "$searchVideoAnswer" == "location" || "$searchVideoAnswer" == "L" || "$searchVideoAnswer" == "l" ]]; then
+		# Read path/to/video
+		read -p "Enter path of the video : " -i "" -e videoPath
+	else
+		echo -e "${red}Invalid argument!${normal}"
+	fi
 }
 
 # ----------\Reduce video size function\----------
 function reduce_video_size() {
-
+	echo "hello"
 }
 
 # ----------\Help function\----------
