add uninstall func

diff --git a/video-tool b/video-tool
--- a/video-tool
+++ b/video-tool
@@ -8,6 +8,9 @@
 #  https://github.com/hessamashari/video-tool.git  #
 ####################################################
 
+	# author : Hessam Ashari
+	# github : https://github.com/hessamashari/video-tool
+	# Email  : hessam.ashari@gmail.com
 
 normal="$(printf '\033[0m')"          # text mode
 # Colors
@@ -245,6 +248,73 @@ function main() {
 		select_video_path
 	else
 		echo -e "${red}Invalid argument!${normal}"
+		exit 1
+	fi
+}
+
+# ----------\Uninstall function\----------
+function uninstall() {
+	clear
+
+	read -p "${red}Are you sure to uninstall video-tool??!! [y/N] ${normal}" deletMusicFinder
+
+	# Remove dependencies
+	if [[ "$deletMusicFinder" == "y" || "$deletMusicFinder" == "Y" ]]; then
+		deleteDependencies="0"
+		# Checking if the distro is DebianBase / ArchBase / RedHatBase / SuseBase and running the correct command
+
+		if pacman -Q &> /dev/null; then # Check Arch
+			sudo pacman -Rs ffmpeg
+			# Check user's entered password
+			if [[ "$?" == "1" ]]; then
+				deleteDependencies="1"
+			fi
+		elif apt list --installed &> /dev/null; then # Check Debian
+			sudo apt remove ffmpeg
+			# Check user's entered password
+			if [[ "$?" == "1" ]]; then
+				deleteDependencies="1"
+			fi
+		elif dnf list &> /dev/null; then # Check Fedora
+			sudo dnf remove ffmpeg
+			# Check user's entered password
+			if [[ "$?" == "1" ]]; then
+				deleteDependencies="1"
+			fi
+		elif zypper search i+ &> /dev/null; then # Check openSUSE
+			sudo zypper remove ffmpeg
+			# Check user's entered password
+			if [[ "$?" == "1" ]]; then
+				deleteDependencies="1"
+			fi
+		else
+			echo -e "${red}Your distro is neither ArchBase or DebianBase or RedHatBase or SuseBase So,
+			 The script is not going to work in your distro and you have uninstall the dependencies manually.${normal}"
+			deleteDependencies="1"
+		fi
+
+		# Removing video-tool Command
+		if [[ "$deleteDependencies" == "0" ]]; then
+			sudo rm -f /usr/bin/video-tool
+			if [[ "$?" == "0" ]]; then
+				echo -e "\n"
+				echo -e "${red}video-tool succesfully uninstalled :( ${normal}"
+			else
+				echo -e "\n"
+				echo -e "${green}video-tool doesn't uninstall succesfully :) ${normal}"
+				exit 1
+			fi
+		else
+			echo -e "\n"
+			echo -e "${green}video-tool doesn't uninstall succesfully :) ${normal}"
+			exit 1
+		fi
+	elif [[ "$deletMusicFinder" == "" || "$deletMusicFinder" == "n" || "$deletMusicFinder" == "N" ]]; then
+		echo -e "\n"
+		echo -e "${green}video-tool is still installed :) ${normal}"
+		return
+	else
+		echo -e "${red}Invalid argument! ${normal}"
 		exit 1
 	fi
 }
